# pr1012 grabside
default_pulls:
  - gateway: jsk_pr1040_.*
default_advertisements:
  - name: /bb_repub
    node: None
    type: publisher
  - name: /rocon/move_to_table/where
    node: None
    type: publisher
